sudo: required

services:
    - docker

language: bash

before_script:
    - docker-compose pull
    - docker-compose up -d --scale web=5
    - docker ps

script:
    - while ! curl --retry 10 --retry-delay 5 -v http://0.0.0.0:8000 >/dev/null; do sleep 1; done